---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./base/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
