---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: cert-manager-webhook-gandi
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/bwolf/cert-manager-webhook-gandi
