---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./base/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  dependsOn:
    - name: cert-manager-webhook-gandi
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRelease
metadata:
  name: cert-manager-webhook-gandi
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: secrets
  chart:
    chart: ./deploy/cert-manager-webhook-gandi
    sourceRef:
      name: cert-manager-webhook-gandi
      kind: GitRepository
    interval: 5m
    valuesFiles:
      - ./deploy/cert-manager-webhook-gandi/values.yaml
  values:
    groupName: acme.0x44.pw
