---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./base/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  dependsOn:
    - name: cert-manager-webhook-gandi
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager-webhook-gandi
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ./deploy/cert-manager-webhook-gandi
      sourceRef:
        kind: GitRepository
        name: cert-manager-webhook-gandi
      interval: 5m
      valuesFiles:
        - ./deploy/cert-manager-webhook-gandi/values.yaml
  dependsOn:
    - name: secrets
  values:
    groupName: acme.0x44.pw
