---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: k8s.gcr.io/external-dns/external-dns
    newTag: v0.10.1
resources:
  - ./namespace.yaml
  - ./cloudflare-api-token.yaml
  - ./deployment.yaml
  - ./serviceaccount.yaml
  - ./clusterrole.yaml
  - ./clusterrolebinding.yaml
