---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emqx
  namespace: emqx
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://repos.emqx.io/charts
      chart: emqx
      version: 4.3.8
      sourceRef:
        kind: HelmRepository
        name: emqx-charts
        namespace: flux-system
      interval: 5m
  values:
    replicaCount: 3
    recreatePods: true
    service:
      type: LoadBalancer
      loadBalancerIP: 10.1.0.1
    ingress:
      dashboard:
        enabled: true
        ingressClassName: istio
        hosts:
          - dashboard.emqx.0x44.pw
      mgmt:
        enabled: true
        ingressClassName: istio
        hosts:
          - api.emqx.0x44.pw
    emqxConfig:
      EMQX_ALLOW_ANONYMOUS: "false"
    emqxAclConfig: >
      {allow, {user, "dashboard"}, subscribe, ["$SYS/#"]}.
      {allow, all, subscribe, ["$SYS/#", {eq, "#"}]}.
      {allow, all}.
    emqxLoadedPlugins: >
      {emqx_management, true}.
      {emqx_recon, true}.
      {emqx_retainer, true}.
      {emqx_dashboard, true}.
      {emqx_telemetry, false}.
      {emqx_rule_engine, true}.
      {emqx_bridge_mqtt, false}.
      {emqx_auth_mnesia, true}.
      {emqx_prometheus, true}.
    emqxLoadedModules: >
      {emqx_mod_presence, true}.
      {emqx_mod_delayed, false}.
      {emqx_mod_rewrite, false}.
      {emqx_mod_subscription, false}.
      {emqx_mod_topic_metrics, true}.
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 150Mi
