---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitea-cert
  namespace: istio-system
spec:
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  secretName: gitea-cert
  dnsNames:
  - git.0x44.pw
