---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: gitea
  labels:
    app: frontend
spec:
  minReadySeconds: 5
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "false"
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: gitea/gitea:1.15.0
        imagePullPolicy: Always
        env:
          - APP_NAME=Gitea
          - USER_UID=1000
          - USER_GID=1000
          - ROOT_URL=https://git.0x44.pw
          - SSH_DOMAIN=git.0x44.pw
          - SSH_PORT=2222
          - HTTP_PORT=80
          - DB_TYPE=postgres
          - DB_HOST=gitea-db:5432
          - DB_NAME=gitea
          - DB_USER=postgres
          - DB_PASSWD=postgres
        ports:
        - containerPort: 5432
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
      - name: database
        image: postgres:alpine
        imagePullPolicy: Always
        env:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=gitea
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgresdb
    volumes:
      - name: postgresdb
        persistentVolumeClaim:
          claimName: gitea-database-pvc
      - name: data
        persistentVolumeClaim:
          claimName: gitea-pvc
