---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: istio-gateway
  namespace: flux-system
spec:
  dependsOn:
    - name: istio-system
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./base/istio/gateway
  prune: true
  validation: client
