---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  chart:
    spec:
      chart: base
      sourceRef:
        kind: HelmRepository
        name: istio-charts
  interval: 1m0s
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: istio-operator
      namespace: istio-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  dependsOn:
    - name: istio-base
  chart:
    spec:
      chart: istiod
      sourceRef:
        kind: HelmRepository
        name: istio-charts
  interval: 1m0s
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: istiod
      namespace: istio-system
    - apiVersion: apps/v1
      kind: Deployment
      name: prometheus
      namespace: istio-system
    - apiVersion: apps/v1
      kind: Deployment
      name: flagger
      namespace: istio-system
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: istio-ingress
spec:
  dependsOn:
    - name: istiod
  chart:
    spec:
      chart: gateway
      sourceRef:
        kind: HelmRepository
        name: istio-charts
  interval: 1m0s
