---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kubebot
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./base/kubebot
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: sop-secrets
    - name: istio-gateway
