apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgDDNr9+htmf0k8+p6kGCVgyfwChOsqGgk7PlSv1ULnf2alCllkXKSc9nXbiZV+1xCcoC4tTiF7a9EPaGiszXEbf3w04Eu8KmDz+9DObQLYFUPpl8EY/nlE66QzkYwVajDlr02xLBBHPtf7G4pb0wawpOmoeHDa/tBJVsq2wHtpfyzWpCb2qxqKxC9XKzuhQJhvpYFmHxLhUYRWGM2xAN5/1A+zsKPRxPqIQE85QoNgUyJkRsQCJFSfiIBtmSTF2oENFQdjM0Fa+Bo5AvzcpgNUM7V9CcsnLq9sp3R4KrDffbFi9ZLV/XMaSMht/l8Q6qfL9t/hTIoBA90DRtfhh4E5ioH2+gvXLg6lDoFCa8qp6n7CF87VnAxqbhpVnTE7nOdgxqmnKBezEOdHJz5nvhMcemM+bKLywhW774E5ju+VdO0XRqayBUdkIJ6O66Bru1fh6tidupk5Xop2mmJ/JFiEIMOEYGcl6UirL5t7xEPg3v1raFHZC/nsANToTM2ZZGDmg2xRqi21Z/qs0cPgvrlGj8mzae0t/IT6q1fHctyNxTxlj1l1z0io9hyUCpQgYhcJNBVw7gdXeF16225A/ZAKRq6DPUGep1NCsvWDhOhxtlN4khWTH0nP9weLHPhtSPWvyt4xtTt17BMQdBTzSsTYyzvi9oOSbMzBhm/f3Ip1SNxYTWa0BXpQho8CBxlwoF4f7fm8oJylmdBNth/tvGtf3ZAA1VzvGNpZ1UeHDbSUkgbPc3kRXqu0U
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager

