apiVersion: v1
data:
    api-token: ENC[AES256_GCM,data:OLWiIFrRsSuZ0+64h6ZHFdCm9Hsv9UXp83P9mUTaIxIvsxMnS/IWd2b7xqdGyaJ5y2qgPfH//4c=,iv:8gf/DJLjKMxv8aZ8LMnuqChFWYaK0MdpMJVxvOpLJPc=,tag:ENYfmo22fr8i1lpzZfjqZg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cloudflare-api-token
    namespace: cert-manager
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-28T15:38:06Z"
    mac: ENC[AES256_GCM,data:aaA6kpsooYB+Tma9q81QNDKW1db+0kZi9nlKBNBuXpVzAV0qSknkY5XprF0RULm984y/en8PhS4WFcZUUF8O3Kt3vzMtYdDO825qC6nHSUs12Oi4bqGjprK5Oipd5sS99h0OMRh495TlWKYoVumjytvLMNwrVcE3M7vrVjr2Y9s=,iv:nx0un5e81S3/9AP0Cvk3CFxIXYT3BuO3ABYkiWRCZIE=,tag:QZu/k4WWY2+HFbzQFE9zPA==,type:str]
    pgp:
        - created_at: "2021-09-28T15:38:02Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1GKz/Q2QO26AQ/+LA1VSZ2m0aKDYvS4S2agI3j9rYpD4rMFabXpMbp2jt3l
            TttjGykbJwYKxAp5cC/I7DsOMLXHmJE4vPHy/umHOx5hUz4mDJHtYy3rFX4GBPVW
            7bDJE6WHRaaoloEp8ywVk0cSV9KemlRQicJcAOSxHTT9E6HMBN/CRnRqSx8gwspO
            ibyM4/QtGpOb6NS8ie/NFZEk2zSY8LwvrPO5vUmeifLGMeHRZwOvGmGBxH27bKsV
            kZn+6+Do276M/qiciMhU3WtIeYejnS2yloueTUQQRt7aZf+KxVmqNPJ/1FYVDMWG
            vBJEXLxwb7Zo+eveKizjQ35SPnx7TEyXBounOyHoXeVoSMaCZwgb7AjhEUNEYchl
            XrvU3rakc2jNbx6zAhHZekX076pR/9hxz+B5V1MRYpGcy/ELNgTLk6ZZliuV+Vwj
            Cg3acKuKvNrNbhiQGRtDyW4ZD2c+VMUrvfqOc9Li3GmoYOq9GOSvDzUkKwyAEasi
            ZrPK/BWLw5X+wz9OX5CV9BT+us0Dqg7KUHym9QmAyoBPxqypWvqKevFuma9HRLoY
            MrYvbgvvGnw3TNfLDRtaFdV5LUgR/q6tPZs9jqfPSOzViFrrSxUvgDQx+iAMRfyX
            dd/M0ORedoEmTY0wkoNWFCAQOEvcCMpOX+SOc5/CmV0pyZOENMhPARWM8LgvWtjU
            aAEJAhWeDh/uZvFuCk+Tvdlwv6RmJCIv3wQJx7M233vGs/L5tQsQhAFH0UjsEHuk
            wfHVC/p7PHwlYVbbKI2Vd2NWZN9VVQ3WgpcT0s5f7E9WfahoCYC40RYp8cGBATj8
            krweH3vFjgyO
            =7/02
            -----END PGP MESSAGE-----
          fp: 3250A9F57F40BB2F8BA51C03F85DEE255243F2FF
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
