---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-proxy-auth-cert
  namespace: istio-system
spec:
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  secretName: ""
  commonName: ""
  dnsNames: []
