---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ianpringle-org-cert
  namespace: istio-system
spec:
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  secretName: ianpringle-org-cert
  commonName: ianpringle.org
  dnsNames:
  - ianpringle.org
  - www.ianpringle.org
