---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
spec:
  targetNamespace: external-dns
  interval: 5m0s
  path: ./kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: external-dns
  dependsOn:
    - name: sop-secrets
  patchesStrategicMerge:
  patchesStrategicMerge:
  - apiVersion:
    kind: Deployment
    metadata:
      name: external-dns
    spec:
      template:
        spec:
          args:
          - --source=service
          - --source=ingress
          - --source=gateway
          - --provider=cloudflare
          - --cloudflare-proxied
          env:
          - name: CF_API_TOKEN:
            valueFrom:
              secretKeyRef:
                name: cloudflare-secrets
                key: api-token
