---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-ingress-app
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/pard68/gitops
    targetRevision: argo
    path: apps/foundation/argocd-ingress/resources
