---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: csi-s3
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: patch-1
  url: https://github.com/pard68/csi-s3
