---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: csi-s3
  namespace: flux-system
spec:
  dependsOn:
    - name: sop-secrets
  interval: 5m0s
  path: ./deploy/kubernetes/
  prune: true
  sourceRef:
    kind: GitRepository
    name: csi-s3
  validation: client
  targetNamespace: kube-system
