apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: k8s.gcr.io/external-dns/external-dns
    newTag: v0.9.0
resources:
  - ./deployment.yaml
  - ./serviceaccount.yaml
  - ./clusterrole.yaml
  - ./clusterrolebinding.yaml
