---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: 0x44-blog
  namespace: flux-system
spec:
  dependsOn:
    - name: istio-gateway
    - name: cert-manager
    - name: external-dns
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./base/0x44-blog
  prune: true
  validation: client
