---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: 0x44-blog
  namespace: flux-system
spec:
  dependsOn:
    - name: istio-gateway
    - name: cert-manager
    - name: external-dns
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./base/generic-site-www
  prune: true
  validation: client
  images:
    - name: placeholder/image
      newName: pard68/0x44
      newTag: latest
  postBuild:
    substitute:
      namespace_name: "0x44-blog"
      cert_name: "0x44-blog-cert"
      host_name: "0x44.pw"
