---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    email: pard@0x44.pw
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - dns01:
        webhook:
          groupName: acme.0x44.pw
          solverName: gandi
          config:
            apiKeySecretRef:
              key: api-token
              name: gandi-credentials
