---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../secrets/cert-manager
  - ./webhooks
  - https://github.com/jetstack/cert-manager/releases/download/v1.5.3/cert-manager.yaml
  - issuer.yaml
patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: cert-manager
      spec:
        template:
          spec:
            containers:
              args:
                - --dns01-recursive-nameservers=\"8.8.8.8:53,1.1.1.1:53\"
