---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.yaml
  - ./webhooks
  - https://github.com/jetstack/cert-manager/releases/download/v1.5.3/cert-manager.yaml
  - issuer.yaml
