---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flagger
  namespace: istio-system
spec:
  chart:
    spec:
      chart: flagger
      sourceRef:
        kind: HelmRepository
        name: flagger
  interval: 1h0m0s
  releaseName: flagger
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    meshProvider: istio
    metricsServer: http://prometheus.istio-system:9090
    includeLabelPrefix: app
