---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: argo
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./manifests/cluster-install/
  prune: true
  sourceRef:
    kind: GitRepository
    name: argo-workflow
  validation: client

