---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: test-proxy-auth
  namespace: flux-system
spec:
  targetNamespace: test-proxy-auth
  dependsOn:
    - name: istio-gateway
    - name: cert-manager
    - name: external-dns
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./base/generic-site
  prune: true
  validation: client
  images:
    - name: placeholder/image
      newName: pard68/0x44
      newTag: latest
  patchesStrategicMerge:
    - apiVersion: networking.istio.io/v1alpha3
      kind: VirtualService
      metadata:
        name: frontend
      spec:
        http:
        - match:
          - uri:
              prefix: /
          route:
          - destination:
              port:
                number: 80
              host: frontend
  postBuild:
    substitute:
      namespace-name: "test-auth-proxy"
      cert-name: "test-auth-proxy"
      host-names-list: "[test-proxy-auth.0x44.pw]"
