---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: test-proxy-auth
  namespace: flux-system
spec:
  targetNamespace: test-proxy-auth
  dependsOn:
    - name: istio-gateway
    - name: cert-manager
    - name: external-dns
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./base/generic-site
  prune: true
  validation: client
  images:
    - name: frontend
      newName: pard68/0x44
      newTag: latest
  patchesStrategicMerge:
    - apiVersion: networking.istio.io/v1alpha3
      kind: Gateway
      metadata:
        name: gateway
      spec:
        servers:
          - port:
            hosts:
              - "test-proxy-auth.0x44.pw"
          - port:
            tls:
              credentialName: test-proxy-auth-cert
            hosts:
              - "test-proxy-auth.x44.pw"
    - apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: test-proxy-auth-cert
        namespace: istio-system
      spec:
        secretName: test-proxy-auth-cert
        commonName: test-proxy-auth.0x44.pw
        dnsNames:
        - test-proxy-auth.0x44.pw
    - apiVersion: networking.istio.io/v1alpha3
      kind: VirtualService
      metadata:
        name: virtual-service
      spec:
        hosts:
        - test-proxy-auth.0x44.pw
        gateways:
        - gateway
        http:
        - match:
          - uri:
              prefix: /
          route:
          - destination:
              port:
                number: 80
              host: frontend
  postBuild:
    substitute:
      namespace_name: "test-auth-proxy"
